modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/endergetic/issues"
license = "https://github.com/team-abnormals/endergetic/blob/main/LICENSE.txt"

[[mods]]
    modId = "endergetic"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    authors = "Team Abnormals"
    credits = "SmellyModder, Endergized, Timinations, and bageldotjpg"
    displayName = "The Endergetic Expansion"
    description = '''
    Ever since the end was first introduced to the game it's always been a dull place; and it has great potential to be something greater. This mod expands the end greatly by adding tons of new biomes, mobs, bosses, items, blocks, etc to the end! Venture to new places like the Poise Forest or explore old places like the chorus biome which have been revamped!
    '''

[[dependencies.endergetic]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.3,1.17)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.endergetic]]
    modId = "forge"
    mandatory = true
    versionRange = "[36.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.endergetic]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.1.0,)"
    ordering = "AFTER"
    side = "BOTH"